try {
    ; Your code that might throw an error
    throw ErrorMsg("Something went wrong!")
}
catch (e) {
    ; Handle the error, e contains the error message
    ; Calling the STR() function will convert e to a string since in some languages like C++ it's not a string.
    print("Caught error: " . STR(e))
}
finally {
    ; Code that will always execute, regardless of an error
    print("Finally block executed")
}